### ISSUE TITLE
Plugin not showing

### ISSUE THREAD

**Issue by schmoelder** [ok97465/spyder_okvim#42]
Hey again,
after updating spyder to 5.1.5, the plugin stopped working. There is no more tab in the preferences. Reinstalling also did not work.

**Comment by ok97465** [comment]
Hi!
I applied a simple fix for spyder 5. Since I'm still in the spyder4, there may be a problem with the current fix.
Also, the Config page doesn't work, but I'm going to take time to think about this problem.
